import Nav from "@/components/nav/Nav";
import type { Metadata } from "next";
import { Bungee } from "next/font/google";

const bungee = Bungee({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={bungee.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
